# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_insumo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.ManyToManyField(to='Inventario.InsumoTipo'),
        ),
    ]
