# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20190401_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='InsumoTipo',
        ),
        migrations.AddField(
            model_name='insumo',
            name='producto',
            field=models.ManyToManyField(to='Inventario.Producto'),
        ),
    ]
