# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_auto_20190401_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='producto',
        ),
        migrations.AddField(
            model_name='insumo',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.TipoInsumo'),
            preserve_default=False,
        ),
    ]
