# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_auto_20190401_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='producto',
            new_name='tipo_insumo',
        ),
    ]
