# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 02:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_auto_20190401_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
