# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-30 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_promocion_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoinsumo',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
