# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='compras_Inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='compras_modulo',
            field=models.BooleanField(default=False),
        ),
    ]
