# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_promocion_promocionproducto'),
        ('Compras', '0002_auto_20190401_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='orden',
            name='productos',
        ),
        migrations.AddField(
            model_name='ordenproducto',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.Orden'),
        ),
        migrations.AddField(
            model_name='ordenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Producto'),
        ),
    ]
