# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 05:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0003_auto_20190401_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.Orden')),
            ],
        ),
    ]
