# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0004_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproducto',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Preparando', 'Preparando'), ('En espera', 'en_espera')], default='en_espera', max_length=250),
            preserve_default=False,
        ),
    ]
