# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0005_ordenproducto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproducto',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Preparando', 'Preparando'), ('en_espera', 'En espera')], max_length=250),
        ),
    ]
