# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0007_factura_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
